apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: eventpipe
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: http
