apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: eventpipe
spec:
  selector:
    app: ingest
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
